name: Docbook Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/student/docbook
            git pull origin main
            docker build -t docbook-app .
            docker rm -f docbook || true
            docker run -d -p 8080:8080 --env-file /home/student/docbook/.env --name docbook docbook-app
