name: Docbook Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/student/docbook

            # Pull latest changes
            git pull origin main

            # Stop existing containers
            docker-compose down || true

            # Build and start services
            docker-compose up -d --build

            # Wait for MySQL to be ready
            sleep 30
